/*
Navicat MySQL Data Transfer

Source Server         : items
Source Server Version : 50045
Source Host           : localhost:3306
Source Database       : items

Target Server Type    : MYSQL
Target Server Version : 50045
File Encoding         : 65001

Date: 2018-11-16 14:32:08
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `detail`
-- ----------------------------
DROP TABLE IF EXISTS `detail`;
CREATE TABLE `detail` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `title` text NOT NULL,
  `btitle` text NOT NULL,
  `price` text NOT NULL,
  `size` text NOT NULL,
  `src` text NOT NULL,
  `model` text NOT NULL,
  `sidebar` text NOT NULL,
  `img` text NOT NULL,
  `ser` text NOT NULL,
  `type` text NOT NULL,
  `alltype` text NOT NULL,
  `sales` text NOT NULL,
  `nav` text NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=65 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of detail
-- ----------------------------
INSERT INTO `detail` VALUES ('1', '黑木森林慕思蛋糕', '8号巧克力与巴旦木杏仁的碰撞', '288', '', '1,2,3,4,5', '', '1', '-1', '10000001', '鲜奶蛋糕', 'MUCH蛋糕', '62', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/list/list.html?type=鲜奶蛋糕_鲜奶蛋糕,/html/detail/detail.html?id=1_8号黑木森林慕思蛋糕');
INSERT INTO `detail` VALUES ('2', '樱香漫漫鲜奶蛋糕', '洁白雅致，细细点缀', '158', '6号,8号,10号', '11,12,13,14', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '11', '-2', '10000002', '鲜奶蛋糕', 'MUCH蛋糕', '23', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/list/list.html?type=鲜奶蛋糕_鲜奶蛋糕,/html/detail/detail.html?id=2_8号樱香漫漫鲜奶蛋糕');
INSERT INTO `detail` VALUES ('3', '朵朵咖啡鲜奶蛋糕', '朵朵咖啡，悦享品质', '158', '6号,8号,10号', '21,22,23,24,25,26', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '21', '-3', '10000003', '鲜奶蛋糕', 'MUCH蛋糕', '49', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/list/list.html?type=鲜奶蛋糕_鲜奶蛋糕,/html/detail/detail.html?id=3_8号朵朵咖啡鲜奶蛋糕');
INSERT INTO `detail` VALUES ('4', '爱的心意鲜奶蛋糕', '', '158', '6号,8号,10号', '31,32,33,34', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '31', '-4', '10000004', '鲜奶蛋糕', 'MUCH蛋糕', '37', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/list/list.html?type=鲜奶蛋糕_鲜奶蛋糕,/html/detail/detail.html?id=4_8号爱的心意鲜奶蛋糕');
INSERT INTO `detail` VALUES ('5', '黑芝麻打开记忆礼盒', '', '68', '', '41,42,43,44', '', '41', '-5', '10000005', '补冬礼盒', '元祖补冬季', '18', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖补冬季_元祖补冬季,/html/list/list.html?type=补冬礼盒_补冬礼盒,/html/detail/detail.html?id=5_黑芝麻糕打开记忆礼盒 ');
INSERT INTO `detail` VALUES ('6', '核枣糕打开记忆礼盒', '入口的幸福，相伴的健康。', '88', '', '51,52,53,54', '', '51', '-6', '10000006', '补冬礼盒', '元祖补冬季', '47', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖补冬季_元祖补冬季,/html/list/list.html?type=补冬礼盒_补冬礼盒,/html/detail/detail.html?id=6_核枣糕打开记忆礼盒 ');
INSERT INTO `detail` VALUES ('7', '贵圆糕打开记忆礼盒', '清香桂圆，流连忘返', '98', '', '61,62,63,64', '', '61', '-7', '10000007', '补冬礼盒', '元祖补冬季', '1', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖补冬季_元祖补冬季,/html/list/list.html?type=补冬礼盒_补冬礼盒,/html/detail/detail.html?id=7_贵圆糕打开记忆礼盒 ');
INSERT INTO `detail` VALUES ('8', '黑芝麻糕礼盒', '浓浓芝麻香，怀念的味道。', '88', '', '71,72,73,74', '', '71', '-8', '10000008', '补冬礼盒', '元祖补冬季', '31', '/index.html_主页 ,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖补冬季_元祖补冬季,/html/list/list.html?type=补冬礼盒_补冬礼盒,/html/detail/detail.html?id=8_黑芝麻糕礼盒 ');
INSERT INTO `detail` VALUES ('9', '元祖旺来凤梨酥', '一款不可多得的伴手礼', '128', '', '81,82,83', '', '81', '-9', '10000009', '糕点礼盒', '元组礼盒', '55', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖礼盒_元祖礼盒,/html/list/list.html?type=糕点礼盒_糕点礼盒,/html/detail/detail.html?id=9_绿豆糕礼盒');
INSERT INTO `detail` VALUES ('10', '坚果礼盒', '巴旦木，黑芝麻。高山与田园两只清隽古调', '98', '', '91,92,93', '', '91', '-10', '100000010', '糕点礼盒', '元组礼盒', '52', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖礼盒_元祖礼盒,/html/list/list.html?type=糕点礼盒_糕点礼盒,/html/detail/detail.html?id=10_坚果礼盒');
INSERT INTO `detail` VALUES ('11', '幸福结果子礼盒', '一款不可多得的伴手礼', '60', '', '101,102,103', '', '101', '-11', '10000011', '糕点礼盒', '元组礼盒', '5', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖礼盒_元祖礼盒,/html/list/list.html?type=糕点礼盒_糕点礼盒,/html/detail/detail.html?id=11_幸福结果子礼盒');
INSERT INTO `detail` VALUES ('12', '绿豆糕礼盒', '炎炎夏日，吹来一股凉风', '98', '', '111,112,113', '', '111', '-12', '100000012', '糕点礼盒', '元组礼盒', '36', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖礼盒_元祖礼盒,/html/list/list.html?type=糕点礼盒_糕点礼盒,/html/detail/detail.html?id=12_绿豆糕礼盒');
INSERT INTO `detail` VALUES ('13', '100型心意卡', '一卡在手，跨地通提', '100', '', '121,122', '', '121', '-13', '100000013', '礼卡', '元祖卡券', '54', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖卡券_元祖卡券,/html/list/list.html?type=礼卡_礼卡,/html/detail/detail.html?id=13_元祖100型心意卡');
INSERT INTO `detail` VALUES ('14', '200型心意卡', '一卡在手，跨地通提', '200', '', '131,132', '', '131', '-14', '10000014', '礼卡', '元祖卡券', '62', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖卡券_元祖卡券,/html/list/list.html?type=礼卡_礼卡,/html/detail/detail.html?id=14_元祖200型心意卡');
INSERT INTO `detail` VALUES ('15', '300型心意卡', '一卡在手，跨地通提', '300', '', '141,142', '', '141', '-15', '10000015', '礼卡', '元祖卡券', '46', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖卡券_元祖卡券,/html/list/list.html?type=礼卡_礼卡,/html/detail/detail.html?id=15_元祖300型心意卡');
INSERT INTO `detail` VALUES ('16', '500型心意卡', '一卡在手，跨地通提', '500', '', '151,152', '', '151', '-16', '10000016', '礼卡', '元祖卡券', '23', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖卡券_元祖卡券,/html/list/list.html?type=礼卡_礼卡,/html/detail/detail.html?id=16_元祖500型心意卡');
INSERT INTO `detail` VALUES ('17', '麻糬枣泥味', 'Q糯的外表下，很有内涵', '10', '', '161', '花生味,枣泥味,芝麻味', '161', '-17', '10000017', '麻糬类', '精致西点', '40', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=精致西点_精致西点,/html/list/list.html?type=麻糬类_麻糬类,/html/detail/detail.html?id=17_麻糬枣泥味');
INSERT INTO `detail` VALUES ('18', '蜂蜜蛋糕', '', '11', '', '171', '抹茶口味,原味', '171', '-18', '10000018', '其他', '精致西点', '0', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=精致西点_精致西点,/html/list/list.html?type=其他_其他,/html/detail/detail.html?id=18_蜂蜜蛋糕原味');
INSERT INTO `detail` VALUES ('19', '小方慕思草莓味', '三点一刻，最期待的享受。', '20', '', '181', '乳酪味,草莓味', '181', '-19', '10000019', '小慕思类', '精致西点', '60', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=精致西点_精致西点,/html/list/list.html?type=小慕思类_小慕思类,/html/detail/detail.html?id=19_小方慕思草莓味');
INSERT INTO `detail` VALUES ('20', '核枣糕礼盒', '入口的幸福，相伴的健康。', '118', '', '191,192,193,194', '', '191', '-20', '10000020', '补冬礼盒', '元祖补冬季', '49', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖补冬季_元祖补冬季,/html/list/list.html?type=补冬礼盒_补冬礼盒,/html/detail/detail.html?id=20_核枣糕礼盒');
INSERT INTO `detail` VALUES ('21', '贵圆糕礼盒', '清香桂圆，流连忘返', '128', '', '201,202,203,204', '', '201', '-21', '10000021', '补冬礼盒', '元祖补冬季', '42', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖补冬季_元祖补冬季,/html/list/list.html?type=补冬礼盒_补冬礼盒,/html/detail/detail.html?id=21_贵圆糕礼盒');
INSERT INTO `detail` VALUES ('22', '琥珀之心芝麻鲜奶蛋糕', '', '158', '6号,8号', '211,212,213,214', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '211', '-22', '10000022', '补冬蛋糕', '元祖补冬季', '62', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖补冬季_元祖补冬季,/html/list/list.html?type=补冬礼盒_补冬礼盒,/html/detail/detail.html?id=22_8号琥珀之心芝麻鲜奶蛋糕');
INSERT INTO `detail` VALUES ('23', '元祖萌虎鲜奶蛋糕', '重返童年时光', '158', '6号,8号', '221,222,223,224', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '221', '-23', '100000023', '鲜奶蛋糕', 'MUCH蛋糕', '15', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/shop-mall/shop-index.html_鲜奶蛋糕,/html/detail/detail.html?id=23_8号元祖萌虎鲜奶蛋糕');
INSERT INTO `detail` VALUES ('24', '坚果大地芝麻鲜奶蛋糕', '', '158', '6号,8号', '231,232,233', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '231', '-24', '10000024', '补冬蛋糕', '元祖补冬季', '15', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖补冬季_元祖补冬季,/html/list/list.html?type=补冬蛋糕_补冬蛋糕,/html/detail/detail.html?id=24_8号坚果大地芝麻鲜奶蛋糕');
INSERT INTO `detail` VALUES ('25', '甜蜜如心鲜奶蛋糕', '牵手的甜蜜，相伴的甜蜜，心与心依偎。', '158', '6号,8号,10号', '241', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '241', '-25', '100000025', '鲜奶蛋糕', 'MUCH蛋糕', '64', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/list/list.html?type=鲜奶蛋糕_鲜奶蛋糕,/html/detail/detail.html?id=25_甜蜜如心鲜奶蛋糕');
INSERT INTO `detail` VALUES ('26', '桃花扇鲜奶蛋糕', '简约不简单', '158', '', '251,252,253', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '251', '-26', '100000026', '鲜奶蛋糕', 'MUCH蛋糕', '63', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/list/list.html?type=鲜奶蛋糕_鲜奶蛋糕,/html/detail/detail.html?id=26_桃花扇鲜奶蛋糕');
INSERT INTO `detail` VALUES ('27', '金蜜蜂鲜奶蛋糕', '如蜜蜂般奋发向上的精神', '158', '6号,8号', '261,262,263,264,265', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '261', '-27', '100000027', '其他', '精致西点', '21', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=精致西点_精致西点,/html/list/list.html?type=其他_其他,/html/detail/detail.html?id=27_金蜜蜂鲜奶蛋糕');
INSERT INTO `detail` VALUES ('28', 'LOVE ME巧克力蛋糕', '爱，是我用心为你描绘的世界。', '158', '6号,8号,10号', '271', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '271', '-28', '100000028', '巧克力蛋糕', 'MUCH蛋糕', '62', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/shop-mall/shop-index.html_巧克力蛋糕,/html/detail/detail.html?id=28_6号LOVE ME巧克力蛋糕');
INSERT INTO `detail` VALUES ('29', '蛋黄酥礼盒', '上海优选伴手礼', '120', '', '281,282,283', '口味随机', '281', '-29', '100000029', '糕点礼盒', '元组礼盒', '39', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖礼盒_元祖礼盒,/html/list/list.html?type=糕点礼盒_糕点礼盒,/html/detail/detail.html?id=29_蛋黄酥礼盒');
INSERT INTO `detail` VALUES ('30', '连枝并头鲜奶蛋糕', '走到了婚姻殿堂，一定是最爱的才在一起', '1140', '', '291', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '291', '-30', '100000030', '多层蛋糕', 'MUCH蛋糕', '58', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/shop-mall/shop-index.html_巧克力蛋糕,/html/detail/detail.html?id=30_连枝并头鲜奶蛋糕');
INSERT INTO `detail` VALUES ('31', '玫瑰热恋鲜奶蛋糕', '一朵玫瑰，一份执守。相爱予狂风，相伴予暖阳', '660', '', '301', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '301', '-31', '100000031', '多层蛋糕', 'MUCH蛋糕', '29', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/shop-mall/shop-index.html_巧克力蛋糕,/html/detail/detail.html?id=31_玫瑰热恋鲜奶蛋糕');
INSERT INTO `detail` VALUES ('32', '百寿延绵鲜奶蛋糕', '岁月留下鲜花的晚香，寿星在祝福声中容颜不老。。。', '1040', '', '311', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '311', '-32', '100000032', '多层蛋糕', 'MUCH蛋糕', '35', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/shop-mall/shop-index.html_巧克力蛋糕,/html/detail/detail.html?id=32_百寿延绵鲜奶蛋糕');
INSERT INTO `detail` VALUES ('33', '天亦有情鲜奶蛋糕', '送给婚礼的祝福，三生三世情缘', '1140', '', '321', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '321', '-33', '100000033', '多层蛋糕', 'MUCH蛋糕', '45', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/shop-mall/shop-index.html_巧克力蛋糕,/html/detail/detail.html?id=33_天亦有情鲜奶蛋糕');
INSERT INTO `detail` VALUES ('34', '粉色恋曲鲜奶蛋糕', '黄玫瑰与粉玫瑰，活力与纯真。', '800', '', '331', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '331', '-34', '100000034', '多层蛋糕', 'MUCH蛋糕', '33', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/shop-mall/shop-index.html_巧克力蛋糕,/html/detail/detail.html?id=34_粉色恋曲鲜奶蛋糕');
INSERT INTO `detail` VALUES ('35', '冬日丹桂慕思蛋糕', '', '188', '6号,8号', '341,342,343,344', '', '341', '-35', '100000035', '补冬蛋糕', '元祖补冬季', '7', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖补冬季_元祖补冬季,/html/list/list.html?type=补冬蛋糕_补冬蛋糕,/html/detail/detail.html?id=35_6号冬日丹桂慕思蛋糕');
INSERT INTO `detail` VALUES ('36', '补冬礼盒', '新品上市，具体发货时间根据门店到货时间安排', '130', '', '351,352,353,354', '', '351', '-36', '100000036', '补冬礼盒', '元祖补冬季', '6', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖补冬季_元祖补冬季,/html/list/list.html?type=补冬礼盒_补冬礼盒,/html/detail/detail.html?id=36_补冬礼盒');
INSERT INTO `detail` VALUES ('37', '我的歌声里鲜奶蛋糕', '听懂歌声，便听懂了世界', '158', '6号,8号,10号', '361', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '361', '-37', '100000037', '鲜奶蛋糕', 'MUCH蛋糕', '50', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/list/list.html?type=鲜奶蛋糕_鲜奶蛋糕,/html/detail/detail.html?id=37_6号我的歌声里鲜奶蛋糕');
INSERT INTO `detail` VALUES ('38', '田园晓美鲜奶蛋糕', '田园风光，一览无余，晨晓', '158', '6号,8号,10号', '371', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '371', '-38', '100000038', '鲜奶蛋糕', 'MUCH蛋糕', '22', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/list/list.html?type=鲜奶蛋糕_鲜奶蛋糕,/html/detail/detail.html?id=38_田园晓美鲜奶蛋糕');
INSERT INTO `detail` VALUES ('39', 'Nice兔meetyou鲜奶蛋糕', '她微笑迎接每天的日出，生活永远快乐着', '158', '6号,8号', '381', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '381', '-39', '100000039', '鲜奶蛋糕', 'MUCH蛋糕', '15', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/list/list.html?type=鲜奶蛋糕_鲜奶蛋糕,/html/detail/detail.html?id=39_Nice兔meetyou鲜奶蛋糕');
INSERT INTO `detail` VALUES ('40', '福鸟咕咕宝鲜奶蛋糕', '福鸟到，吉利到！', '158', '6号,8号', '391,392', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '391', '-40', '100000040', '巧克力蛋糕', 'MUCH蛋糕', '35', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/list/list.html?type=巧克力蛋糕_巧克力蛋糕,/html/detail/detail.html?id=40_福鸟咕咕宝鲜奶蛋糕');
INSERT INTO `detail` VALUES ('41', '清风有信慕思蛋糕', '摇动树叶如铃，在盛夏的午后，清风送来一封信', '188', '6号,8号,10号', '401', '', '401', '-41', '100000041', '慕思蛋糕', 'MUCH蛋糕', '11', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/list/list.html?type=慕思蛋糕_慕思蛋糕,/html/detail/detail.html?id=41_清风有信慕思蛋糕');
INSERT INTO `detail` VALUES ('42', '香芒飘飘慕思蛋糕', '芒果阵阵清香，口口饱满', '188', '6号,8号', '411', '', '411', '-42', '100000042', '慕思蛋糕', 'MUCH蛋糕', '5', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/list/list.html?type=慕思蛋糕_慕思蛋糕,/html/detail/detail.html?id=42_香芒飘飘慕思蛋糕');
INSERT INTO `detail` VALUES ('43', '前程似锦鲜奶蛋糕', '紫玫瑰的浪漫与真情，在雪地里拥抱未来', '1040', '', '421', '香芋+香芋（网红款）,水果+布丁,布丁+香芋,布丁+燕麦,水果+香芋,水果+燕麦,香芋+燕麦', '421', '-43', '100000043', '多层蛋糕', 'MUCH蛋糕', '9', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=MUCH蛋糕_MUCH蛋糕,/html/list/list.html?type=多层蛋糕_多层蛋糕,/html/detail/detail.html?id=43_前程似锦鲜奶蛋糕');
INSERT INTO `detail` VALUES ('44', '乌龙茶礼盒', '每一片茶叶的挑选，每一杯好茶的历练', '248', '', '431,432,433', '', '431', '-44', '100000044', '糕点礼盒', '元组礼盒', '9', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖礼盒_元祖礼盒,/html/list/list.html?type=糕点礼盒_糕点礼盒,/html/detail/detail.html?id=44_乌龙茶礼盒');
INSERT INTO `detail` VALUES ('45', '2入蛋生报喜礼盒', '弥月不迟，礼赠新生。', '28', '', '441,442,443', '', '441', '-45', '100000045', '糕点礼盒', '元组礼盒', '30', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖礼盒_元祖礼盒,/html/list/list.html?type=糕点礼盒_糕点礼盒,/html/detail/detail.html?id=45_2入蛋生报喜礼盒');
INSERT INTO `detail` VALUES ('46', '咖啡礼盒（5入）', '停下来，享受生活', '58', '', '451,452', '', '451', '-46', '100000046', '糕点礼盒', '元组礼盒', '27', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖礼盒_元祖礼盒,/html/list/list.html?type=糕点礼盒_糕点礼盒,/html/detail/detail.html?id=46_Much咖啡礼盒');
INSERT INTO `detail` VALUES ('47', '桂圆核桃糕', '', '10', '', '461', '', '461', '-47', '100000047', '西点卷类', '精致西点', '50', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=精致西点_精致西点,/html/list/list.html?type=西点卷类_西点卷类,/html/detail/detail.html?id=47_桂圆核桃糕');
INSERT INTO `detail` VALUES ('48', '优酪球巧克力', '奶酪邂逅提子，浓香酸甜的满足感', '10', '', '471', '', '471', '-48', '100000048', '其他', '精致西点', '36', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=精致西点_精致西点,/html/list/list.html?type=其他_其他,/html/detail/detail.html?id=48_优酪球巧克力');
INSERT INTO `detail` VALUES ('49', '西点卷', '', '10', '', '481,482', '抹茶红豆卷,肉松卷,草莓卷,虎皮卷,香槟葡萄卷,咖啡卷', '481', '-49', '100000049', '西点卷类', '精致西点', '61', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=精致西点_精致西点,/html/list/list.html?type=西点卷类_西点卷类,/html/detail/detail.html?id=49_小西点卷');
INSERT INTO `detail` VALUES ('50', '三角cheese cake', '让您充分体验奶酪的至尊享受', '22', '', '491', '', '491', '-50', '100000050', '小慕思类', '精致西点', '1', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=精致西点_精致西点,/html/list/list.html?type=小慕思类_小慕思类,/html/detail/detail.html?id=50_三角cheese cake');
INSERT INTO `detail` VALUES ('51', '红蛋', '', '8', '', '501', '', '501', '-51', '100000051', '其他', '精致西点', '', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=精致西点_精致西点,/html/list/list.html?type=其他_其他,/html/detail/detail.html?id=51_红蛋');
INSERT INTO `detail` VALUES ('52', '168型水果提货券', '', '168', '', '511', '', '511', '-52', '100000052', '水果券', '元祖卡券', '', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖卡券_元祖卡券,/html/list/list.html?type=水果券_水果券,/html/detail/detail.html?id=52_168型水果提货券');
INSERT INTO `detail` VALUES ('53', '20型西点券', '一券在手，多种款式，任君挑选', '20', '', '521', '', '521', '-53', '100000053', '西点券', '元祖卡券', '', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖卡券_元祖卡券,/html/list/list.html?type=西点券_西点券,/html/detail/detail.html?id=53_20型西点券');
INSERT INTO `detail` VALUES ('54', '10型西点券', '一券在手，多种款式，任君挑选', '10', '', '531', '', '531', '-54', '100000054', '西点券', '元祖卡券', '', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖卡券_元祖卡券,/html/list/list.html?type=西点券_西点券,/html/detail/detail.html?id=54_10型西点券');
INSERT INTO `detail` VALUES ('55', '100型西点券', '一券在手，多种款式，任君挑选', '100', '', '541', '', '541', '-55', '100000055', '西点券', '元祖卡券', '', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖卡券_元祖卡券,/html/list/list.html?type=西点券_西点券,/html/detail/detail.html?id=55_100型西点券');
INSERT INTO `detail` VALUES ('56', '218型蛋糕券', '', '218', '', '551', '', '551', '-56', '100000056', '蛋糕券', '元祖卡券', '', 'ex.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖卡券_元祖卡券,/html/list/list.html?type=蛋糕券_蛋糕券,/html/detail/detail.html?id=56_218型蛋糕券');
INSERT INTO `detail` VALUES ('57', '158型蛋糕券', '', '158', '', '561', '', '561', '-57', '100000057', '蛋糕券', '元祖卡券', '', 'ex.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖卡券_元祖卡券,/html/list/list.html?type=蛋糕券_蛋糕券,/html/detail/detail.html?id=57_158型蛋糕券');
INSERT INTO `detail` VALUES ('58', '288型蛋糕券', '', '288', '', '571', '', '571', '-58', '100000058', '蛋糕券', '元祖卡券', '', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖卡券_元祖卡券,/html/list/list.html?type=蛋糕券_蛋糕券,/html/detail/detail.html?id=58_288型蛋糕券');
INSERT INTO `detail` VALUES ('59', '16号鲜奶蛋糕电子券', '每笔订单限购10张电子券。', '568', '', '581', '', '581', '-59', '100000059', '电子券', '元祖卡券', '', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖卡券_元祖卡券,/html/list/list.html?type=电子券_电子券,/html/detail/detail.html?id=59_16号鲜奶蛋糕电子券');
INSERT INTO `detail` VALUES ('60', '14号鲜奶蛋糕电子券', '每笔订单限购10张电子券。', '468', '', '591', '', '591', '-60', '100000060', '电子券', '元祖卡券', '', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖卡券_元祖卡券,/html/list/list.html?type=电子券_电子券,/html/detail/detail.html?id=60_14号鲜奶蛋糕电子券');
INSERT INTO `detail` VALUES ('61', '10号慕思蛋糕电子券', '每笔订单限购10张电子券。', '358', '', '601', '', '601', '-61', '100000061', '电子券', '元祖卡券', '', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖卡券_元祖卡券,/html/list/list.html?type=电子券_电子券,/html/detail/detail.html?id=61_10号慕思蛋糕电子券');
INSERT INTO `detail` VALUES ('62', '100型西点电子券', '每笔订单限购10张电子券。', '100', '', '611', '', '611', '-62', '100000062', '电子券', '元祖卡券', '', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖卡券_元祖卡券,/html/list/list.html?type=电子券_电子券,/html/detail/detail.html?id=62_100型西点电子券');
INSERT INTO `detail` VALUES ('63', '台湾柿礼盒', '足以颠覆你的【柿界观】', '168', '', '621,622,623,624', '', '621', '-63', '100000063', '水果礼盒', '元组礼盒', '', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖礼盒_元祖礼盒,/html/list/list.html?type=水果礼盒_水果礼盒,/html/detail/detail.html?id=63_台湾柿礼盒');
INSERT INTO `detail` VALUES ('64', '台湾葡萄柚礼盒', '果肉细嫩 色泽深红 水份爆汁 新鲜美味', '168', '', '631,632,633', '', '631', '-64', '100000064', '水果礼盒', '元组礼盒', '', '/index.html_主页,/html/shop-mall/shop-index.html_元祖商城,/html/list/list.html?alltype=元祖礼盒_元祖礼盒,/html/list/list.html?type=水果礼盒_水果礼盒,/html/detail/detail.html?id=64_台湾葡萄柚礼盒');
